# Generated by Django 5.0.2 on 2024-03-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=60)),
                ('userPhoneNumber', models.CharField(max_length=13)),
                ('userProfileUrl', models.CharField(max_length=1000)),
                ('userCreatedAt', models.DateTimeField(auto_now=True)),
                ('userModifiedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
