# Generated by Django 5.0.2 on 2024-03-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='userId',
            new_name='userUID',
        ),
    ]
